import type {Metadata} from 'next';
import {Roboto} from 'next/font/google';
import './globals.css';
import {ReactNode} from 'react';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

interface ClientLayoutProps {
  children: ReactNode;
}

function ClientLayout({children}: ClientLayoutProps) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  'use client';
  return (
    <ClientLayout>
      {children}
    </ClientLayout>
  );
}

